"""add price_cm_min column

Revision ID: 0e115e02cd33
Revises: ec7d988a3237
Create Date: 2026-04-01 21:17:59.809919
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e115e02cd33'
down_revision: Union[str, None] = 'ec7d988a3237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('price_cm_min', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'price_cm_min')
    # ### end Alembic commands ###
