"""add price_updated_at column

Revision ID: 49b9ca92abb1
Revises: f4760deddcaa
Create Date: 2026-04-03 01:58:25.713414
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b9ca92abb1'
down_revision: Union[str, None] = 'f4760deddcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('price_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'price_updated_at')
    # ### end Alembic commands ###
