"""create cards table with collection fields

Revision ID: 6798a4734c6a
Revises: 
Create Date: 2026-03-29 17:21:55.930372
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6798a4734c6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('frame_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('atk', sa.Integer(), nullable=True),
    sa.Column('def', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('attribute', sa.String(length=20), nullable=True),
    sa.Column('archetype', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('price_cardmarket', sa.Float(), nullable=True),
    sa.Column('price_tcgplayer', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'rarity', 'condition', 'lang', name='uq_card_variant')
    )
    op.create_index(op.f('ix_cards_card_id'), 'cards', ['card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_card_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
