"""add price_manual flag

Revision ID: cd259cd0665d
Revises: d4ed5765159c
Create Date: 2026-03-31 17:32:30.312950
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd259cd0665d'
down_revision: Union[str, None] = 'd4ed5765159c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('price_manual', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'price_manual')
    # ### end Alembic commands ###
