"""add price_source column

Revision ID: ec7d988a3237
Revises: cd259cd0665d
Create Date: 2026-04-01 18:26:31.595416
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7d988a3237'
down_revision: Union[str, None] = 'cd259cd0665d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('price_source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'price_source')
    # ### end Alembic commands ###
