"""add price_cm_avg and price_cm_median columns

Revision ID: f4760deddcaa
Revises: 0e115e02cd33
Create Date: 2026-04-01 22:28:12.888465
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4760deddcaa'
down_revision: Union[str, None] = '0e115e02cd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('price_cm_avg', sa.Float(), nullable=True))
    op.add_column('cards', sa.Column('price_cm_median', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'price_cm_median')
    op.drop_column('cards', 'price_cm_avg')
    # ### end Alembic commands ###
